[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.1"
quilt_loader = "0.17.4"

qsl = "3.0.0-beta.14+1.19.2"
isnrmn = "v1_03"
mixin_extras = "0.1.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

qsl_core_base = { module = "org.quiltmc.qsl.core:qsl_base", version.ref = "qsl" }
qsl_core_networking = { module = "org.quiltmc.qsl.core:networking", version.ref = "qsl" }
isnrmn = { module = "maven.modrinth:isnrmn", version.ref = "isnrmn" }
mixin_extras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixin_extras" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
# [bundles]
# example = ["example-a", "example-b", "example-c"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
